services:
  - type: web
    name: my-django-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-database
          property: connectionString
      - key: SECRET_KEY
        value: your_secret_key_here
      - key: DEBUG
        value: "True"
    buildCommand: docker build -t my-django-app .
    startCommand: docker run -p 8000:8000 my-django-app

  - type: postgresql
    name: my-database
    plan: free
    properties:
      databaseName: mydatabase
      user: myuser
      password: mypassword
